name: Tracking issue for bootcamp.
description: Use this template for tracking bootcamp bugs, incomprehensible instructions, and other issues.
labels: Bootcamp
fields:
  - name: problemType
    type: dropdown
    description: What is the type of the problem ?
    options:
      - Workshop incomprehension
      - Outdated code, libs
      - Error
    required: true
  - name: errorDescription
    type: input
    description: What is the error, add screenshot if necessary
    placeholder: |
      ERROR in ./src/components/Button/Button.styles.js 3:0-30, Module not found: Error: Can't resolve './Button'
    required: false
