name: Tracking issue for bootcamp.
description: Use this template for tracking bootcamp bugs, incomprehensible instructions, and other issues.
labels: ["Bootcamp report"]
body:
  - type: textarea
    attributes:
      label: Describe the bug,
      description: Also include a description of how to reproduce the bug
    validations:
      required: true

  - type: input
    id: file
    attributes:
      label: In which file is the bug located?
      description: If the error is not in a file, please write "none"
      placeholder: "src/screens/ExampleScreen.tsx"

- type: input
    id: error
    attributes:
      label: What is the error displayed 
      description: If the error is not in a file, please write "none"
      placeholder: "ERROR in ./src/components/Button/Button.styles.js 3:0-30, Module not found: Error: Can't resolve './Button'"

  - type: textarea
    attributes:
      label: Additional info
      description: Screenshots, logs, etc.
    validations:
      required: false
