---
name: Challenge report
description: Use this template for tracking bootcamp challenges bugs, incomprehensible instructions, and other issues.
labels: ["challenges"]
body:
  - type: textarea
    id: bugDescription
    attributes:
      label: Describe the bug, the incomprehension
      description: Also include a description of how to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: additionalInfo
    attributes:
      label: Additional info
      description: Screenshots, logs, etc.
    validations:
      required: false
---

