name: Bug report
description: For issues with the bootcamp.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        Before creating a **bug report**, please check the following:
          * Ensure you're running the latest version release.
          * Ensure there isn't an existing issue for your bug. If there is, leave a comment on the existing issue.

  - type: textarea
    attributes:
      label: Describe the bug
      description: Also include a description of how to reproduce the bug
    validations:
      required: true

  - type: input
    id: file
    attributes:
      label: In which file the bug is located ?
      description: If the error is not in a file, please write "none"
      placeholder: "src/screens/ExampleScreen.tsx"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Screenshots, logs, etc.
    validations:
      required: false
